name: check

on: push

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        run: rustup toolchain install --no-self-update

      - name: Install dev tools
        uses: taiki-e/install-action@288e746965032cfcc232e09af2daf5f23c14d780 # v2.86.1
        with:
          tool: cargo-llvm-cov@0.8.7,prek@0.4.13,sqlx-cli@0.9.0

      - name: Run pre-commit hooks
        run: prek run --all-files
